services:
  database:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Qwert1!Asdf2?Yxcv3"
      ACCEPT_EULA: "Y"

  app:
    build:
      context: .
      dockerfile: El-Proyecte-Grande/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - database
    environment:
      CONNECTIONSTRINGS__DEFAULTCONNECTION:  Server=database;Database=ElProyecteGrandeDb;User Id=sa;Password=Qwert1!Asdf2?Yxcv3;Encrypt=false;
    
