version: '3.4'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin12345Admin
  app:
    ports:
      - 8080:80
    build:
      context: .
      dockerfile: El-Proyecte-Grande/Dockerfile
    depends_on:
      - database
    environment:
      CONNECTIONSTRINGS__DEFAULTCONNECTION: Server=database;Database=ElProyecteGrandeDb;User Id=sa;Password=Admin12345Admin;Encrypt=false;
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: ../
      dockerfile: client/Dockerfile
    ports:
      - 5173:5173
    tty: true