version: '3.4'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin12345Admin
  app:
    ports:
      - 8080:80
    build:
      context: .
      dockerfile: El-Proyecte-Grande/Dockerfile
    depends_on:
      - database
    environment:
      CONNECTIONSTRINGS__DEFAULTCONNECTION: Server=database;Database=ElProyecteGrandeDb;User Id=sa;Password=Admin12345Admin;Encrypt=false;
      ISSUERSIGNINGKEY: MySecretKey!!!needsToBeLonger?Maybe
      VALIDISSUER: ElProyecteAuth
      VALIDAUDIENCE: ElProyecteAuth
      ROLES_1: Admin
      ROLES_2: User
      MOVIEDB_API_KEY: 81041f1501b21c327e1c6644a030c201
      OMDB_API_KEY: de5ff22f
    command: ["./wait-for-it.sh", "database:1433", "--", "dotnet", "run"]
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    tty: true
    environment:
      VITE_PROXY: http://app:80