# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      VALIDISSUER: ${{ secrets.VALIDISSUER }}
      VALIDAUDIENCE: ${{ secrets.VALIDAUDIENCE }}
      ISSUERSIGNINGKEY: ${{ secrets.ISSUERSIGNINGKEY }}
      CONNECTIONSTRINGS__DEFAULTCONNECTION: ${{ secrets.CONNECTIONSTRINGS__DEFAULTCONNECTION }}
      ROLES_1: ${{ secrets.ROLES_1 }}
      ROLES_2: ${{ secrets.ROLES_2 }}
      MOVIEDB_API_KEY: ${{ secrets.MOVIEDB_API_KEY }}
      OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies IntegrationTests
      run: dotnet restore
      working-directory: ./El-Proyecte-Grande/El-Proyecte-Grande-IntegrationTests
    - name: Build IntegrationTests
      run: dotnet build --no-restore
      working-directory: ./El-Proyecte-Grande/El-Proyecte-Grande-IntegrationTests
    - name: IntegrationTests
      run: dotnet test --no-build --verbosity normal
      working-directory: ./El-Proyecte-Grande/El-Proyecte-Grande-IntegrationTests
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push
      working-directory: ./El-Proyecte-Grande

  redeploy-on-render:
    runs-on: ubuntu-latest
    steps:
      - name: Redeploy backend service
        run: |
            curl ${{ secrets.RENDER_BACKEND_URL }}
      - name: Redeploy frontend service
        run: |
            curl ${{ secrets.RENDER_FRONTEND_URL }}
